### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by stevepeak** [asyncy/components#3]
Hey @fatihacet we had a new contributor submit this project (I just committed it not author 😉 )

The goal was to get the default bootstrap theme here and get storybook running at https://storybook.asyncy.com (which it is). The author applied just a couple style changes. But I'm looking for a quick review of the structure and organization.

Thanks!!

**Comment by fatihacet** [comment]
Hey @stevepeak 👋

I take a look at the folder structure/organization and it LGTM. I believe it's pretty much the default Vue CLI project. 🤔

Although, I have a question about vendoring bootstrap and font-awesome stuff. Why do we need to do something like that? 😕 

PS: I didn't really take look into the Vue components. Let me know if you want me to review them too.

**Comment by stevepeak** [comment]
🙇Thank you @fatihacet 

> question about vendoring bootstrap and font-awesome stuff

We have multiple UI frontends and would like to have a single repository with reusable components that can be tested, [visually diff](https://loki.js.org) and branded.

No need to dig deeper 👍
